import type { ThemePackDefinition } from '@/design/factory/recipe-types'

export const THEME_PACKS: Record<ThemePackDefinition['key'], ThemePackDefinition> = {
  'yelp-local': {
    key: 'yelp-local',
    label: 'Yelp Local',
    productFamily: 'directory',
    brandPack: 'directory-clean',
    navbar: 'compact-bar',
    footer: 'columns-footer',
    homeLayout: 'listing-home',
    motionPack: 'minimal',
    defaultTaskTemplates: {
      listing: 'listing-directory',
      classified: 'classified-market',
      profile: 'profile-business',
    },
    notes: ['Search-first utility layout', 'Business trust cues', 'Directory-first homepage rhythm'],
  },
  'directory-premium': {
    key: 'directory-premium',
    label: 'Directory Premium',
    productFamily: 'directory',
    brandPack: 'market-utility',
    navbar: 'utility-bar',
    footer: 'minimal-footer',
    homeLayout: 'listing-home',
    motionPack: 'utility-snappy',
    defaultTaskTemplates: {
      listing: 'listing-showcase',
      classified: 'classified-market',
      profile: 'profile-business',
    },
    notes: ['Sharper commerce feel', 'Denser utility surfaces', 'Premium marketplace tone'],
  },
  'medium-journal': {
    key: 'medium-journal',
    label: 'Medium Journal',
    productFamily: 'editorial',
    brandPack: 'editorial-luxe',
    navbar: 'editorial-bar',
    footer: 'editorial-footer',
    homeLayout: 'article-home',
    motionPack: 'editorial-soft',
    defaultTaskTemplates: {
      article: 'article-journal',
      profile: 'profile-business',
    },
    notes: ['Reading-first layout', 'Calmer typography', 'Long-form bias'],
  },
  'magazine-contrast': {
    key: 'magazine-contrast',
    label: 'Magazine Contrast',
    productFamily: 'editorial',
    brandPack: 'editorial-luxe',
    navbar: 'editorial-bar',
    footer: 'editorial-footer',
    homeLayout: 'article-home',
    motionPack: 'editorial-soft',
    defaultTaskTemplates: {
      article: 'article-editorial',
      profile: 'profile-business',
    },
    notes: ['Bolder cover-story feel', 'Magazine blocks', 'Higher contrast editorial rhythm'],
  },
  'pinterest-creator': {
    key: 'pinterest-creator',
    label: 'Pinterest Creator',
    productFamily: 'visual',
    brandPack: 'studio-dark',
    navbar: 'floating-bar',
    footer: 'dense-footer',
    homeLayout: 'image-profile-home',
    motionPack: 'studio-stagger',
    defaultTaskTemplates: {
      image: 'image-masonry',
      profile: 'profile-creator',
      article: 'article-editorial',
    },
    notes: ['Visual board feel', 'Masonry image rhythm', 'Creator-first supporting lanes'],
  },
  'visual-portfolio': {
    key: 'visual-portfolio',
    label: 'Visual Portfolio',
    productFamily: 'visual',
    brandPack: 'studio-dark',
    navbar: 'floating-bar',
    footer: 'dense-footer',
    homeLayout: 'image-profile-home',
    motionPack: 'studio-stagger',
    defaultTaskTemplates: {
      image: 'image-portfolio',
      profile: 'profile-creator',
      article: 'article-editorial',
    },
    notes: ['Portfolio-style hero', 'Large showcase panels', 'Less noisy support content'],
  },
  'curation-library': {
    key: 'curation-library',
    label: 'Curation Library',
    productFamily: 'curation',
    brandPack: 'editorial-luxe',
    navbar: 'editorial-bar',
    footer: 'editorial-footer',
    homeLayout: 'image-profile-home',
    motionPack: 'editorial-soft',
    defaultTaskTemplates: {
      sbm: 'sbm-library',
      profile: 'profile-business',
      article: 'article-journal',
    },
    notes: ['Collection shelves', 'Library tone', 'Bookmarks over generic cards'],
  },
  'curation-warm': {
    key: 'curation-warm',
    label: 'Curation Warm',
    productFamily: 'curation',
    brandPack: 'editorial-luxe',
    navbar: 'editorial-bar',
    footer: 'editorial-footer',
    homeLayout: 'image-profile-home',
    motionPack: 'editorial-soft',
    defaultTaskTemplates: {
      sbm: 'sbm-curation',
      profile: 'profile-business',
      article: 'article-editorial',
    },
    notes: ['Warmer curation palette', 'Board-style modules', 'Human-curated feel'],
  },
}
